export const PORTFOLIO_LIST = 'PORTFOLIO_LIST';

export const FETCH_INSTRUMENT_HISTORY_RESPONSE = 'FETCH_CRYPTO_HISTORY_RESPONSE';
export const FETCH_INSTRUMENT_HISTORY_ERROR = 'FETCH_CRYPTO_HISTORY_ERROR';

export const FETCH_ALL_ACTIVITY_RESPONSE = 'FETCH_ALL_ACTIVITY_RESPONSE';
export const FETCH_ALL_ACTIVITY_ERROR = 'FETCH_ALL_ACTIVITY_ERROR';



