export const PORTFOLIO_LIST = 'PORTFOLIO_LIST';
export const PORTFOLIO_BY_CODE = 'PORTFOLIO_BY_CODE';

export const FETCH_INSTRUMENT_HISTORY_RESPONSE = 'FETCH_CRYPTO_HISTORY_RESPONSE';
export const FETCH_INSTRUMENT_HISTORY_ERROR = 'FETCH_CRYPTO_HISTORY_ERROR';

export const FETCH_ALL_ACTIVITY_RESPONSE = 'FETCH_ALL_ACTIVITY_RESPONSE';
export const FETCH_ALL_ACTIVITY_ERROR = 'FETCH_ALL_ACTIVITY_ERROR';

export const FETCH_ACTIVITY_BY_CODE_RESPONSE = 'FETCH_ACTIVITY_BY_CODE_RESPONSE';
export const FETCH_ACTIVITY_BY_CODE_ERROR = 'FETCH_ACTIVITY_BY_CODE_ERROR';